<Window x:Class="TeklaSubComponentAttributesList.MainWindow"
        xmlns:UIControls="clr-namespace:Tekla.Structures.Dialog.UIControls;assembly=Tekla.Structures.Dialog"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:local="clr-namespace:TeklaSubComponentAttributesList"
        mc:Ignorable="d"
        Title="Demo app" Height="350" Width="500">
    <Grid>
        <Grid.ColumnDefinitions>
            <ColumnDefinition/>
            <ColumnDefinition Width="auto"/>
            <ColumnDefinition/>
        </Grid.ColumnDefinitions>
        <Grid.RowDefinitions>
            <RowDefinition/>
            <RowDefinition Height="auto"/>
            <RowDefinition/>
        </Grid.RowDefinitions>

        <StackPanel Orientation="Vertical"
            Grid.Row="0"
            Grid.Column="1">
            
        <TextBlock 
            Text="Attribute file testing app"
            HorizontalAlignment="Center"
            FontWeight="Bold"
            FontSize="15"
            />

        <TextBlock
           x:Name="ConnectionLabelTextBlock"
            d:Text="test string as placeholder"
            HorizontalAlignment="Center"
           />
            
        </StackPanel>
        <StackPanel Orientation="Vertical"
                    Grid.Row="1" Grid.Column="1"
                    >

            <StackPanel Orientation="Horizontal" Margin="5">
                <TextBlock Text="Select component:"/>
                <UIControls:WpfComponentCatalog
                    x:Name="componentCatalog"
                    SelectClicked="componentCatalog_SelectClicked"
                    SelectionDone="componentCatalog_SelectionDone"
                    />
                
            </StackPanel>
            <StackPanel Orientation="Horizontal" Margin="5">
                <TextBlock Text="Name:" Margin="0,0,20,0" Width="50"/>
                <TextBox
                    x:Name="componentNameBox"
                    Width="120"
                    Height="25"/>
            </StackPanel>
            <StackPanel Orientation="Horizontal" Margin="5">
                <TextBlock Text="Number:" Margin="0,0,20,0" Width="50"/>
                <TextBox
                    x:Name="componentNumberBox"
                    Width="120"
                    Height="25"/>
            </StackPanel>
            <ComboBox
                x:Name="attributesCb"
                Width="120"
                Margin="5"/>

        </StackPanel>
                    

    </Grid>
</Window>
